apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "whizard-agent-proxy.fullname" . }}
  namespace: {{ include "whizard-agent-proxy.namespace" . }}
  labels:
    {{- include "whizard-agent-proxy.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "whizard-agent-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "whizard-agent-proxy.selectorLabels" . | nindent 8 }}
    spec:
      {{- if or .Values.imagePullSecrets .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- include "whizard-agent-proxy.imagePullSecrets" (dict "Values" .Values "imagePullSecrets" .Values.imagePullSecrets) | indent 8 }}
      {{- end }}
      serviceAccountName: {{ include "whizard-agent-proxy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          args: 
            {{- if eq .Values.global.clusterInfo.role "host" }}
            - --gateway.address=http://gateway-whizard-operated.kubesphere-monitoring-system.svc:9090
            {{- else }}
            - --gateway.address={{ .Values.config.gatewayUrl }}
            {{- end }}
            {{- if .Values.global.clusterInfo.name }}
            - --tenant={{ .Values.global.clusterInfo.name }}
            {{- else }}
            - --tenant={{ .Values.config.tenant }}
            {{- end }}
            {{- range .Values.args }}
            - {{ . }}
            {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.imageRegistry | default .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
