/*
Copyright 2021 The KubeSphere authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/kubesphere/paodin-monitoring/pkg/api/monitoring/v1alpha1"
	scheme "github.com/kubesphere/paodin-monitoring/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// StoresGetter has a method to return a StoreInterface.
// A group's client should implement this interface.
type StoresGetter interface {
	Stores(namespace string) StoreInterface
}

// StoreInterface has methods to work with Store resources.
type StoreInterface interface {
	Create(ctx context.Context, store *v1alpha1.Store, opts v1.CreateOptions) (*v1alpha1.Store, error)
	Update(ctx context.Context, store *v1alpha1.Store, opts v1.UpdateOptions) (*v1alpha1.Store, error)
	UpdateStatus(ctx context.Context, store *v1alpha1.Store, opts v1.UpdateOptions) (*v1alpha1.Store, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Store, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.StoreList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Store, err error)
	StoreExpansion
}

// stores implements StoreInterface
type stores struct {
	client rest.Interface
	ns     string
}

// newStores returns a Stores
func newStores(c *MonitoringV1alpha1Client, namespace string) *stores {
	return &stores{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the store, and returns the corresponding store object, and an error if there is any.
func (c *stores) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Store, err error) {
	result = &v1alpha1.Store{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("stores").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Stores that match those selectors.
func (c *stores) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.StoreList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.StoreList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("stores").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested stores.
func (c *stores) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("stores").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a store and creates it.  Returns the server's representation of the store, and an error, if there is any.
func (c *stores) Create(ctx context.Context, store *v1alpha1.Store, opts v1.CreateOptions) (result *v1alpha1.Store, err error) {
	result = &v1alpha1.Store{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("stores").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(store).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a store and updates it. Returns the server's representation of the store, and an error, if there is any.
func (c *stores) Update(ctx context.Context, store *v1alpha1.Store, opts v1.UpdateOptions) (result *v1alpha1.Store, err error) {
	result = &v1alpha1.Store{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("stores").
		Name(store.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(store).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *stores) UpdateStatus(ctx context.Context, store *v1alpha1.Store, opts v1.UpdateOptions) (result *v1alpha1.Store, err error) {
	result = &v1alpha1.Store{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("stores").
		Name(store.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(store).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the store and deletes it. Returns an error if one occurs.
func (c *stores) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("stores").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *stores) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("stores").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched store.
func (c *stores) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Store, err error) {
	result = &v1alpha1.Store{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("stores").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
