/*
Copyright 2021 The KubeSphere authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/kubesphere/paodin-monitoring/pkg/api/monitoring/v1alpha1"
	scheme "github.com/kubesphere/paodin-monitoring/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ThanosReceiveIngestorsGetter has a method to return a ThanosReceiveIngestorInterface.
// A group's client should implement this interface.
type ThanosReceiveIngestorsGetter interface {
	ThanosReceiveIngestors(namespace string) ThanosReceiveIngestorInterface
}

// ThanosReceiveIngestorInterface has methods to work with ThanosReceiveIngestor resources.
type ThanosReceiveIngestorInterface interface {
	Create(ctx context.Context, thanosReceiveIngestor *v1alpha1.ThanosReceiveIngestor, opts v1.CreateOptions) (*v1alpha1.ThanosReceiveIngestor, error)
	Update(ctx context.Context, thanosReceiveIngestor *v1alpha1.ThanosReceiveIngestor, opts v1.UpdateOptions) (*v1alpha1.ThanosReceiveIngestor, error)
	UpdateStatus(ctx context.Context, thanosReceiveIngestor *v1alpha1.ThanosReceiveIngestor, opts v1.UpdateOptions) (*v1alpha1.ThanosReceiveIngestor, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ThanosReceiveIngestor, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ThanosReceiveIngestorList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ThanosReceiveIngestor, err error)
	ThanosReceiveIngestorExpansion
}

// thanosReceiveIngestors implements ThanosReceiveIngestorInterface
type thanosReceiveIngestors struct {
	client rest.Interface
	ns     string
}

// newThanosReceiveIngestors returns a ThanosReceiveIngestors
func newThanosReceiveIngestors(c *MonitoringV1alpha1Client, namespace string) *thanosReceiveIngestors {
	return &thanosReceiveIngestors{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the thanosReceiveIngestor, and returns the corresponding thanosReceiveIngestor object, and an error if there is any.
func (c *thanosReceiveIngestors) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ThanosReceiveIngestor, err error) {
	result = &v1alpha1.ThanosReceiveIngestor{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("thanosreceiveingestors").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ThanosReceiveIngestors that match those selectors.
func (c *thanosReceiveIngestors) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ThanosReceiveIngestorList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ThanosReceiveIngestorList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("thanosreceiveingestors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested thanosReceiveIngestors.
func (c *thanosReceiveIngestors) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("thanosreceiveingestors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a thanosReceiveIngestor and creates it.  Returns the server's representation of the thanosReceiveIngestor, and an error, if there is any.
func (c *thanosReceiveIngestors) Create(ctx context.Context, thanosReceiveIngestor *v1alpha1.ThanosReceiveIngestor, opts v1.CreateOptions) (result *v1alpha1.ThanosReceiveIngestor, err error) {
	result = &v1alpha1.ThanosReceiveIngestor{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("thanosreceiveingestors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(thanosReceiveIngestor).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a thanosReceiveIngestor and updates it. Returns the server's representation of the thanosReceiveIngestor, and an error, if there is any.
func (c *thanosReceiveIngestors) Update(ctx context.Context, thanosReceiveIngestor *v1alpha1.ThanosReceiveIngestor, opts v1.UpdateOptions) (result *v1alpha1.ThanosReceiveIngestor, err error) {
	result = &v1alpha1.ThanosReceiveIngestor{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("thanosreceiveingestors").
		Name(thanosReceiveIngestor.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(thanosReceiveIngestor).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *thanosReceiveIngestors) UpdateStatus(ctx context.Context, thanosReceiveIngestor *v1alpha1.ThanosReceiveIngestor, opts v1.UpdateOptions) (result *v1alpha1.ThanosReceiveIngestor, err error) {
	result = &v1alpha1.ThanosReceiveIngestor{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("thanosreceiveingestors").
		Name(thanosReceiveIngestor.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(thanosReceiveIngestor).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the thanosReceiveIngestor and deletes it. Returns an error if one occurs.
func (c *thanosReceiveIngestors) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("thanosreceiveingestors").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *thanosReceiveIngestors) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("thanosreceiveingestors").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched thanosReceiveIngestor.
func (c *thanosReceiveIngestors) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ThanosReceiveIngestor, err error) {
	result = &v1alpha1.ThanosReceiveIngestor{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("thanosreceiveingestors").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
