{{- if .Values.adapter.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "whizard.adapter.fullname" . }}
  namespace: {{ include "whizard.namespace" . }}
  labels:
    app: {{ include "whizard.adapter.fullname" . }}
    {{- include "whizard.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "whizard.adapter.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "whizard.adapter.fullname" . }}
    spec:
      serviceAccountName: {{ include "whizard.adapter.serviceAccountName" . }}
    {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
      {{- include "whizard.imagePullSecrets" . | indent 8 }}
    {{- end }}
      containers:
        - name: adapter
          args:
          {{- if .Values.adapter.defaultServiceReference }}
          - --default-whizard-service={{ .Values.adapter.defaultServiceReference.namespace }}.{{ .Values.adapter.defaultServiceReference.name }}
          {{- else if .Values.service.enabled }}
          - --default-whizard-service={{ include "whizard.namespace" . }}.{{ include "whizard.service.crname" . }}
          {{- end }}
          {{- if .Values.adapter.defaultStorageReference }}
          - --default-whizard-storage={{ .Values.adapter.defaultStorageReference.namespace }}.{{ .Values.adapter.defaultStorageReference.name }}
          {{- else if .Values.storage.create }}
          - --default-whizard-storage={{ include "whizard.namespace" . }}.{{ include "whizard.storage.crname" . }}
          {{- else }}
          - --default-whizard-storage={{ include "whizard.namespace" . }}.remote
          {{- end }}       
          - --default-whizard-configmap={{ include "whizard.namespace" . }}.{{ include "whizard.fullname" . }}-config
          - --web-enabled={{ .Values.adapter.web.enabled }}
          - --kubesphere-adapter-enabled={{ .Values.adapter.kubesphereAdapter.enabled }}
          image: "{{ .Values.global.imageRegistry | default .Values.adapter.image.registry }}/{{ .Values.adapter.image.repository }}:{{ .Values.adapter.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.adapter.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9091
          readinessProbe:
            httpGet:
              path: /readyz
              port: 9091
          {{- with .Values.adapter.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with (include "whizard.adapter.nodeSelector" .) }}
      nodeSelector:
        {{- . | nindent 8 }}
      {{- end }}
      {{- with .Values.adapter.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.adapter.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
