/*
Copyright 2021 The KubeSphere authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kubesphere/paodin-monitoring/pkg/api/monitoring/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeThanoses implements ThanosInterface
type FakeThanoses struct {
	Fake *FakeMonitoringV1alpha1
	ns   string
}

var thanosesResource = schema.GroupVersionResource{Group: "monitoring", Version: "v1alpha1", Resource: "thanoses"}

var thanosesKind = schema.GroupVersionKind{Group: "monitoring", Version: "v1alpha1", Kind: "Thanos"}

// Get takes name of the thanos, and returns the corresponding thanos object, and an error if there is any.
func (c *FakeThanoses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Thanos, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(thanosesResource, c.ns, name), &v1alpha1.Thanos{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Thanos), err
}

// List takes label and field selectors, and returns the list of Thanoses that match those selectors.
func (c *FakeThanoses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ThanosList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(thanosesResource, thanosesKind, c.ns, opts), &v1alpha1.ThanosList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ThanosList{ListMeta: obj.(*v1alpha1.ThanosList).ListMeta}
	for _, item := range obj.(*v1alpha1.ThanosList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested thanoses.
func (c *FakeThanoses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(thanosesResource, c.ns, opts))

}

// Create takes the representation of a thanos and creates it.  Returns the server's representation of the thanos, and an error, if there is any.
func (c *FakeThanoses) Create(ctx context.Context, thanos *v1alpha1.Thanos, opts v1.CreateOptions) (result *v1alpha1.Thanos, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(thanosesResource, c.ns, thanos), &v1alpha1.Thanos{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Thanos), err
}

// Update takes the representation of a thanos and updates it. Returns the server's representation of the thanos, and an error, if there is any.
func (c *FakeThanoses) Update(ctx context.Context, thanos *v1alpha1.Thanos, opts v1.UpdateOptions) (result *v1alpha1.Thanos, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(thanosesResource, c.ns, thanos), &v1alpha1.Thanos{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Thanos), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeThanoses) UpdateStatus(ctx context.Context, thanos *v1alpha1.Thanos, opts v1.UpdateOptions) (*v1alpha1.Thanos, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(thanosesResource, "status", c.ns, thanos), &v1alpha1.Thanos{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Thanos), err
}

// Delete takes name of the thanos and deletes it. Returns an error if one occurs.
func (c *FakeThanoses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(thanosesResource, c.ns, name), &v1alpha1.Thanos{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeThanoses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(thanosesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ThanosList{})
	return err
}

// Patch applies the patch and returns the patched thanos.
func (c *FakeThanoses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Thanos, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(thanosesResource, c.ns, name, pt, data, subresources...), &v1alpha1.Thanos{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Thanos), err
}
