/*
Copyright 2021 The KubeSphere authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kubesphere/paodin/pkg/api/monitoring/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRulers implements RulerInterface
type FakeRulers struct {
	Fake *FakeMonitoringV1alpha1
	ns   string
}

var rulersResource = schema.GroupVersionResource{Group: "monitoring", Version: "v1alpha1", Resource: "rulers"}

var rulersKind = schema.GroupVersionKind{Group: "monitoring", Version: "v1alpha1", Kind: "Ruler"}

// Get takes name of the ruler, and returns the corresponding ruler object, and an error if there is any.
func (c *FakeRulers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Ruler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(rulersResource, c.ns, name), &v1alpha1.Ruler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Ruler), err
}

// List takes label and field selectors, and returns the list of Rulers that match those selectors.
func (c *FakeRulers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RulerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(rulersResource, rulersKind, c.ns, opts), &v1alpha1.RulerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RulerList{ListMeta: obj.(*v1alpha1.RulerList).ListMeta}
	for _, item := range obj.(*v1alpha1.RulerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested rulers.
func (c *FakeRulers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(rulersResource, c.ns, opts))

}

// Create takes the representation of a ruler and creates it.  Returns the server's representation of the ruler, and an error, if there is any.
func (c *FakeRulers) Create(ctx context.Context, ruler *v1alpha1.Ruler, opts v1.CreateOptions) (result *v1alpha1.Ruler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(rulersResource, c.ns, ruler), &v1alpha1.Ruler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Ruler), err
}

// Update takes the representation of a ruler and updates it. Returns the server's representation of the ruler, and an error, if there is any.
func (c *FakeRulers) Update(ctx context.Context, ruler *v1alpha1.Ruler, opts v1.UpdateOptions) (result *v1alpha1.Ruler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(rulersResource, c.ns, ruler), &v1alpha1.Ruler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Ruler), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRulers) UpdateStatus(ctx context.Context, ruler *v1alpha1.Ruler, opts v1.UpdateOptions) (*v1alpha1.Ruler, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(rulersResource, "status", c.ns, ruler), &v1alpha1.Ruler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Ruler), err
}

// Delete takes name of the ruler and deletes it. Returns an error if one occurs.
func (c *FakeRulers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(rulersResource, c.ns, name, opts), &v1alpha1.Ruler{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRulers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(rulersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.RulerList{})
	return err
}

// Patch applies the patch and returns the patched ruler.
func (c *FakeRulers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Ruler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(rulersResource, c.ns, name, pt, data, subresources...), &v1alpha1.Ruler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Ruler), err
}
