/*
Copyright 2021 The KubeSphere authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kubesphere/paodin/pkg/api/monitoring/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeThanosReceiveIngestors implements ThanosReceiveIngestorInterface
type FakeThanosReceiveIngestors struct {
	Fake *FakeMonitoringV1alpha1
	ns   string
}

var thanosreceiveingestorsResource = schema.GroupVersionResource{Group: "monitoring", Version: "v1alpha1", Resource: "thanosreceiveingestors"}

var thanosreceiveingestorsKind = schema.GroupVersionKind{Group: "monitoring", Version: "v1alpha1", Kind: "ThanosReceiveIngestor"}

// Get takes name of the thanosReceiveIngestor, and returns the corresponding thanosReceiveIngestor object, and an error if there is any.
func (c *FakeThanosReceiveIngestors) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ThanosReceiveIngestor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(thanosreceiveingestorsResource, c.ns, name), &v1alpha1.ThanosReceiveIngestor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ThanosReceiveIngestor), err
}

// List takes label and field selectors, and returns the list of ThanosReceiveIngestors that match those selectors.
func (c *FakeThanosReceiveIngestors) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ThanosReceiveIngestorList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(thanosreceiveingestorsResource, thanosreceiveingestorsKind, c.ns, opts), &v1alpha1.ThanosReceiveIngestorList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ThanosReceiveIngestorList{ListMeta: obj.(*v1alpha1.ThanosReceiveIngestorList).ListMeta}
	for _, item := range obj.(*v1alpha1.ThanosReceiveIngestorList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested thanosReceiveIngestors.
func (c *FakeThanosReceiveIngestors) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(thanosreceiveingestorsResource, c.ns, opts))

}

// Create takes the representation of a thanosReceiveIngestor and creates it.  Returns the server's representation of the thanosReceiveIngestor, and an error, if there is any.
func (c *FakeThanosReceiveIngestors) Create(ctx context.Context, thanosReceiveIngestor *v1alpha1.ThanosReceiveIngestor, opts v1.CreateOptions) (result *v1alpha1.ThanosReceiveIngestor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(thanosreceiveingestorsResource, c.ns, thanosReceiveIngestor), &v1alpha1.ThanosReceiveIngestor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ThanosReceiveIngestor), err
}

// Update takes the representation of a thanosReceiveIngestor and updates it. Returns the server's representation of the thanosReceiveIngestor, and an error, if there is any.
func (c *FakeThanosReceiveIngestors) Update(ctx context.Context, thanosReceiveIngestor *v1alpha1.ThanosReceiveIngestor, opts v1.UpdateOptions) (result *v1alpha1.ThanosReceiveIngestor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(thanosreceiveingestorsResource, c.ns, thanosReceiveIngestor), &v1alpha1.ThanosReceiveIngestor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ThanosReceiveIngestor), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeThanosReceiveIngestors) UpdateStatus(ctx context.Context, thanosReceiveIngestor *v1alpha1.ThanosReceiveIngestor, opts v1.UpdateOptions) (*v1alpha1.ThanosReceiveIngestor, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(thanosreceiveingestorsResource, "status", c.ns, thanosReceiveIngestor), &v1alpha1.ThanosReceiveIngestor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ThanosReceiveIngestor), err
}

// Delete takes name of the thanosReceiveIngestor and deletes it. Returns an error if one occurs.
func (c *FakeThanosReceiveIngestors) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(thanosreceiveingestorsResource, c.ns, name), &v1alpha1.ThanosReceiveIngestor{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeThanosReceiveIngestors) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(thanosreceiveingestorsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ThanosReceiveIngestorList{})
	return err
}

// Patch applies the patch and returns the patched thanosReceiveIngestor.
func (c *FakeThanosReceiveIngestors) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ThanosReceiveIngestor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(thanosreceiveingestorsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ThanosReceiveIngestor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ThanosReceiveIngestor), err
}
