/*
Copyright 2021 The KubeSphere authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// CompactListerExpansion allows custom methods to be added to
// CompactLister.
type CompactListerExpansion interface{}

// CompactNamespaceListerExpansion allows custom methods to be added to
// CompactNamespaceLister.
type CompactNamespaceListerExpansion interface{}

// IngesterListerExpansion allows custom methods to be added to
// IngesterLister.
type IngesterListerExpansion interface{}

// IngesterNamespaceListerExpansion allows custom methods to be added to
// IngesterNamespaceLister.
type IngesterNamespaceListerExpansion interface{}

// RuleListerExpansion allows custom methods to be added to
// RuleLister.
type RuleListerExpansion interface{}

// RuleNamespaceListerExpansion allows custom methods to be added to
// RuleNamespaceLister.
type RuleNamespaceListerExpansion interface{}

// RuleGroupListerExpansion allows custom methods to be added to
// RuleGroupLister.
type RuleGroupListerExpansion interface{}

// RuleGroupNamespaceListerExpansion allows custom methods to be added to
// RuleGroupNamespaceLister.
type RuleGroupNamespaceListerExpansion interface{}

// RulerListerExpansion allows custom methods to be added to
// RulerLister.
type RulerListerExpansion interface{}

// RulerNamespaceListerExpansion allows custom methods to be added to
// RulerNamespaceLister.
type RulerNamespaceListerExpansion interface{}

// ServiceListerExpansion allows custom methods to be added to
// ServiceLister.
type ServiceListerExpansion interface{}

// ServiceNamespaceListerExpansion allows custom methods to be added to
// ServiceNamespaceLister.
type ServiceNamespaceListerExpansion interface{}

// StorageListerExpansion allows custom methods to be added to
// StorageLister.
type StorageListerExpansion interface{}

// StorageNamespaceListerExpansion allows custom methods to be added to
// StorageNamespaceLister.
type StorageNamespaceListerExpansion interface{}

// StoreListerExpansion allows custom methods to be added to
// StoreLister.
type StoreListerExpansion interface{}

// StoreNamespaceListerExpansion allows custom methods to be added to
// StoreNamespaceLister.
type StoreNamespaceListerExpansion interface{}

// TenantListerExpansion allows custom methods to be added to
// TenantLister.
type TenantListerExpansion interface{}

// TenantNamespaceListerExpansion allows custom methods to be added to
// TenantNamespaceLister.
type TenantNamespaceListerExpansion interface{}
