# 
# Copyright 2024 the Whizard Authors.
# 
# Licensed under Apache License, Version 2.0 with a few additional conditions.
# 
# You may obtain a copy of the License at
# 
#     https://github.com/WhizardTelemetry/whizard/blob/main/LICENSE
# 

name: WorkFlow for Building monitoring-agent-proxy image

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/build-monitoring-agent-proxy.yaml'
      - 'build/monitoring-agent-proxy/**'
      - 'cmd/monitoring-agent-proxy/**'
      - 'pkg/monitoring-agent-proxy/**'
      - 'go.mod'
      - 'go.sum'

env:
  REPO: kubesphere

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Build Image for monitoring-agent-proxy
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.17.x

      - uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Image for monitoring-agent-proxy
        run: |
          tag=$(cat VERSION | tr -d " \t\n\r")
          make docker-build-monitoring-agent-proxy -e REPO=${{ env.REPO }} -e TAG=$tag
          docker push ${{ env.REPO }}/whizard-monitoring-agent-proxy:$tag